name: swatmf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - notebook
  - shapely
  - pandas
  - matplotlib
  - pyshp
  - numpy
  - flopy
  - scipy
  - pip:
    - pyemu
    - tqdm
    - hydroeval
    - termcolor
    